export const LOAD_QUESTIONS = "LOAD_QUESTIONS";
export const LOADED_QUESTIONS = "LOADED_QUESTIONS";
export const FAILED_TO_LOAD_QUESTIONS = "FAILED_TO_LOAD_QUESTIONS";
export const LOAD_QUESTION = "LOAD_QUESTION";
export const LOADED_QUESTION = "LOADEDQUESTION";
export const FAILED_TO_LOAD_QUESTION = "FAILED_TO_LOAD_QUESTION";